import 'package:dropdown_plus/dropdown_plus.dart';
import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';
import 'package:velocity_x/velocity_x.dart';

class SearchPageTextFields extends StatefulWidget {
  const SearchPageTextFields({Key? key}) : super(key: key);

  @override
  _SearchPageTextFieldsState createState() => _SearchPageTextFieldsState();
}

class _SearchPageTextFieldsState extends State<SearchPageTextFields> {
  var _color = 0xffff1f1f1;
  @override
  Widget build(BuildContext context) {
    return Column(
      children: [
        TextDropdownFormField(
          options: [
            "Ahmadpur East",
            "Ahmed Nager Chatha",
            "Ali Khan Abad",
            "Alipur",
            "Arifwala",
            "Attock",
            "Bhera",
            "Bhalwal",
            "Bahawalnagar",
            "Bahawalpur",
            "Bhakkar",
            "Burewala",
            "Chenab Nagar",
            "Chillianwala",
            "Choa Saidanshah",
            "Chakwal",
            "Chak Jhumra",
            "Chichawatni",
            "Chiniot",
            "Chishtian",
            "Chunian",
            "Dajkot",
            "Daska",
            "Davispur",
            "Darya Khan",
            "Dera Ghazi Khan",
            "Dhaular",
            "Dina",
            "Dinga",
            "Dhudial Chakwal",
            "Dipalpur",
            "Faisalabad",
            "Fateh Jang",
            "Ghakhar Mandi",
            "Gojra",
            "Gujranwala",
            "Gujrat",
            "Gujar Khan",
            "Harappa",
            "Hafizabad",
            "Haroonabad",
            "Hasilpur",
            "Haveli Lakha",
            "Jalalpur Jattan",
            "Jampur",
            "Jaranwala",
            "Jhang",
            "Jhelum",
            "Kallar Syedan",
            "Kalabagh",
            "Karor Lal Esan",
            "Kasur",
            "Kamalia",
            "Kāmoke",
            "Khanewal",
            "Khanpur",
            "Khanqah Sharif",
            "Kharian",
            "Khushab",
            "Kot Adu",
            "Jauharabad",
            "Lahore",
            "Islamabad",
            "Lalamusa",
            "Layyah",
            "Lawa Chakwal",
            "Liaquat Pur",
            "Lodhran",
            "Malakwal",
            "Mamoori",
            "Mailsi",
            "Mandi Bahauddin",
            "Mian Channu",
            "Mianwali",
            "Miani",
            "Multan",
            "Murree",
            "Muridke",
            "Mianwali Bangla",
            "Muzaffargarh",
            "Narowal",
            "Nankana Sahib",
            "Okara",
            "Renala Khurd",
            "Pakpattan",
            "Pattoki",
            "Pindi Bhattian",
            "Pind Dadan Khan",
            "Pir Mahal",
            "Qaimpur",
            "Qila Didar Singh",
            "Raiwind",
            "Rajanpur",
            "Rahim Yar Khan",
            "Rawalpindi",
            "Sadiqabad",
            "Sagri",
            "Sahiwal",
            "Sambrial",
            "Samundri",
            "Sangla Hill",
            "Sarai Alamgir",
            "Sargodha",
            "Shakargarh",
            "Sheikhupura",
            "Shujaabad",
            "Sialkot",
            "Sohawa",
            "Soianwala",
            "Siranwali",
            "Tandlianwala",
            "Talagang",
            "Taxila",
            "Toba Tek Singh",
            "Vehari",
            "Wah Cantonment",
            "Wazirabad",
            "Yazman",
            "Zafarwal",
          ],
          decoration: InputDecoration(
              fillColor: Color(_color),
              filled: true,
              hintText: "Select City",
              prefixIcon: Image.asset(
                "assets/signup/area.png",
                height: 7,
                width: 7,
              ).pOnly(left: 10, right: 10, top: 10, bottom: 10),
              suffixIcon: Icon(Icons.arrow_drop_down),
              ),
          dropdownHeight: 120,
        ),
        
        TextDropdownFormField(
          options: [
            "A+",
            "A-",
            "B+",
            "B-",
            "AB+",
            "AB-",
            "O+",
            "O-"
          ],
          decoration: InputDecoration(
            border: OutlineInputBorder(
                borderSide: BorderSide.none,
              ),
               fillColor: Color(_color),
              filled: true,
              hintText: "Blood Group",
              prefixIcon: Image.asset(
                "assets/signup/blood_group.png",
                height: 10,
                width: 10,
              ).pOnly(left: 10, right: 10, top: 10, bottom: 10),
              
              suffixIcon: Icon(Icons.arrow_drop_down),
              ),
          dropdownHeight: 120,
        ),
        ],
    );
  }
}
